# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Telegraph' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Telegraph

# pod "BSImagePicker", "~> 2.8"

platform :ios, '8.0'
use_frameworks!

pod 'HMQRCodeScanner'


end


